<%@ Page Title="" Language="C#" MasterPageFile="~/design/MasterPage.master" AutoEventWireup="true" CodeFile="Aboutus.aspx.cs" Inherits="Aboutus" %>

<%@ Import Namespace="Artisteer" %>
<%@ Register TagPrefix="artisteer" Namespace="Artisteer" %>
<%@ Register TagPrefix="art" TagName="DefaultMenu" Src="aboutmenu.ascx" %> 
<%@ Register TagPrefix="art" TagName="DefaultHeader" Src="DefaultHeader.ascx" %> 
<%@ Register TagPrefix="art" TagName="DefaultSidebar1" Src="DefaultSidebar1.ascx" %>
          

<asp:Content ID="PageTitle" ContentPlaceHolderID="TitleContentPlaceHolder" Runat="Server">
    About us||
</asp:Content>

<asp:Content ID="HeaderContent" ContentPlaceHolderID="HeaderContentPlaceHolder" Runat="Server">
    <art:DefaultHeader ID="DefaultHeader" runat="server" />
</asp:Content>
<asp:Content ID="MenuContent" ContentPlaceHolderID="MenuContentPlaceHolder" Runat="Server">
    <art:DefaultMenu ID="DefaultMenuContent" runat="server" />
</asp:Content>
<asp:Content ID="SideBar1" ContentPlaceHolderID="Sidebar1ContentPlaceHolder" Runat="Server">
    <art:DefaultSidebar1 ID="DefaultSidebar1Content" runat="server" />
</asp:Content>

<asp:Content ID="SheetContent" ContentPlaceHolderID="SheetContentPlaceHolder" Runat="Server">

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<head>
		<title>Photo generated by VisualLightBox.com</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
		<meta name="keywords" content="Photo, VisualLightBox, LightBox, Photo Gallery, Online Picture Gallery, Photo Album Creator" />
		<meta name="description" content="Photo created with VisualLightBox, a free wizard program that helps you easily generate beautiful Lightbox-style web photo galleries" />
		<link rel="shortcut icon" href="favicon.ico" />
		
		<!-- Start VisualLightBox.com HEAD section -->
		<link rel="stylesheet" href="engine/css/vlightbox1.css" type="text/css" />
		<link rel="stylesheet" href="engine/css/visuallightbox.css" type="text/css" media="screen" />
<script src="engine/js/jquery.min.js" type="text/javascript"></script>
		<script src="engine/js/visuallightbox.js" type="text/javascript"></script>
		<!-- End VisualLightBox.com HEAD section -->
		
	</head>
	<body>
	
	<!-- Start VisualLightBox.com BODY section id=1 -->
	
    
	<script src="engine/js/vlbdata1.js" type="text/javascript"></script>
	<!-- End VisualLightBox.com BODY section -->
	
	</body>
</html>



<artisteer:Article ID="Article1"  Caption="Introduction" runat="server"><ContentTemplate>
    
    
    <div id="vlightbox1">
	<a class="vlightbox1" href="data/images1/medicines.jpg" title="Medicines">
    <img src="data/thumbnails1/medicines.jpg" alt="Jake Duldulao" style="float:left;"/>
    </a>
	</div>
    <p>
    <a href="javascript:void(0)" title="link"></a>, <a class="visited" href="javascript:void(0)" title="visited link"></a>, 
     <a class="hover" href="javascript:void(0)" title="hovered link"></a> The objectives of electronic drug guide book
      were to determine the effectiveness of electronic drug guide book for common illness among children (Pediatric patients)
       and to develop a web application that sustained the drug information and specifications.
        In this chapter, the results made on the evaluation on the effectiveness of electronic 
        drug guide book for common illness among children were discussed and the data gathered
         from the respondents of the study are presented and interpreted.
         The researcher made an application (web application) for drug guide 
         to measure its effectiveness in terms of browsing the drug specifications.</p>
    <p>
    	<span class="art-button-wrapper">
    		<span class="l"> </span>
    		<span class="r"> </span>
    		<a class="art-button" href="javascript:void(0)">Read more...</a>
    	</span>
    </p>
    </ContentTemplate></artisteer:Article>


    <artisteer:Article ID="Article2" Caption="About us:" runat="server"><ContentTemplate><p><sup></sup>Electronic drug guide book <sub></sub>MEDICATIONS <a href="#" title="test link">Explore</a>. 
    	 <cite></cite>. 
         <br />
         <br />
    	<p>Nowadays, Medicine is considered as life’s necessity. Medication errors were threatening public health. According 
        to a landmark 1999 Institute of Medicine report, between 44,000 and 98,000 Americans die annually due to medical errors. 
        A Latin word “ars medicina” meaning "the art of healing". It is a branch of the health sciences and it’s a sector of
         public life concerning the maintenance and restoration of human health through the study, diagnosis, treatment and 
         possible prevention of disease, injury and other damage to a body or mind. Some people didn’t know what are the 
         importance of every specific medicine. There are some people who self-medicate, without knowing its adverse effect 
         to our health. This is why it is important to ask doctor’s prescription about all the medicines you are going to take. 
         Genetically, Medicine makes us feel better when we are sick.
 Drug guide book is one example for taking medicines guidelines. Web Applications has a big help for us in terms of
  transactions and businesses. We can make a website for a specific field of study. There are many existing
   Drug Guide Book today specially in other rich countries which has a big help for people. 
   The Electronic Drug Guide Book in an application which we will be guided for medication 
   upon browsing in the Internet. It is technologically designed and implemented to other 
   countries and has a big purpose in guidelines for medication processes. Electronic Drug 
   Guide Book is   exciting medical information application for medical guidelines in the 
   Internet to help improve your health care now and in the future, besides, 
   it will keep you healthy and medically aware.
</p>
<br />
        <p>The main objective of the study was to determine the effectiveness of Electronic Drug Guide Book for common illnesses among children and to develop an electronic drug guide book (web application).
	The study was limited to all parents who have children ages one to twelve years old; Pharmacists and Pediatricians. Electronic Drug Guide Book was designed and limited to evaluate whether the system will be more
    effective and more useful to the society especially to the parents for them also to get more details and information about how to cure common illness encountered by their kids. The system did not cover all the aspects of
     Electronic Drug guide Book. It was limited for children ages 0-12. Above 12 years old were not visible in the system. 10 common illnesses will be conducted as example illnesses. The study focused only for some kind of illnesses and how to cure it using medicine (drug) guidelines.
             The study hypothesized that using the Electronic Drug Guide Book (web application) instead of reading the drug guide book manually will be a big help to us especially for the parents.</p>

    	</p>
        
        <hr />
        <p>Increasing numbers of medicines are available to
us every day and it is important to manage them correctly
if they are to be effective. An average, active
older adult is taking three to five medicines every day.
Studies show that older adults are often unaware of
why they take specific drugs, the name of the drugs
they take, possible side effects, or the dose for specific
medications. Having these simple pieces of information
on a wallet card and with you at all times could
save your life. Senior Information & Assistance has
cards that you can use.</p>
    <p>Drug abuse is a disorder that is characterized by a destructive pattern of using a substance that leads to significant problems or distress.
Drug addiction is a disease that is characterized by a destructive pattern of drug abuse that leads to significant problems involving tolerance to or withdrawal from the substance,
 as well as other problems use of the substance can cause for the sufferer.
Drug abuse and addiction are unfortunately quite common, affecting 7% and more than 2% of people at some point in their lives, respectively.
Dual diagnosis refers to the presence of both a drug-abuse or dependence issue in addition to a serious mental-health problem in an individual.
Virtually any substance whose ingestion can result in a euphoric ("high") feeling can be abused.
Inhalants like household cleaners are some of the most commonly abused substances.
While the specific physical and psychological effects of drug abuse and addiction tend to vary based on the particular substance involved,
 the general effects of abuse or addiction to any drug can be devastating.</p>

 <p>Dosage Form (DF) is defined as the physical form of a dose of a chemical compound used as a drug or medication 
        intended for administration or consumption. Common dosage forms include pill, tablet, or capsule, drink or syrup,
         aerosol or inhaler, liquid injection, pure powder or solid crystal (e.g., via oral ingestion or freebase smoking),
          and natural or herbal form such as plant or food of sorts, among many others. The route of administration (ROA)
           for drug delivery is dependent on the dosage form of the substance.</p>
        </ContentTemplate></artisteer:Article>

        
        <br />


        
      
    	
           </ContentTemplate></artisteer:Article>
    
    </div>
</asp:Content>
