<%@ Page Title="" Language="C#" MasterPageFile="~/design/MasterPage.master" AutoEventWireup="true" CodeFile="Thrush.aspx.cs" Inherits="Thrush" %>

<%@ Import Namespace="Artisteer" %>
<%@ Register TagPrefix="artisteer" Namespace="Artisteer" %>
<%@ Register TagPrefix="art" TagName="DefaultMenu" Src="DefaultMenu.ascx" %> 
<%@ Register TagPrefix="art" TagName="DefaultHeader" Src="DefaultHeader.ascx" %> 
<%@ Register TagPrefix="art" TagName="DefaultSidebar1" Src="DefaultSidebar1.ascx" %>
          

<asp:Content ID="PageTitle" ContentPlaceHolderID="TitleContentPlaceHolder" Runat="Server">
   Thrush||
</asp:Content>

<asp:Content ID="HeaderContent" ContentPlaceHolderID="HeaderContentPlaceHolder" Runat="Server">
    <art:DefaultHeader ID="DefaultHeader" runat="server" />
</asp:Content>
<asp:Content ID="MenuContent" ContentPlaceHolderID="MenuContentPlaceHolder" Runat="Server">
    <art:DefaultMenu ID="DefaultMenuContent" runat="server" />
</asp:Content>
<asp:Content ID="SideBar1" ContentPlaceHolderID="Sidebar1ContentPlaceHolder" Runat="Server">
    <art:DefaultSidebar1 ID="DefaultSidebar1Content" runat="server" />
</asp:Content>

<asp:Content ID="SheetContent" ContentPlaceHolderID="SheetContentPlaceHolder" Runat="Server">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<head>
		<title>Photo generated by VisualLightBox.com</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
		<meta name="keywords" content="Photo, VisualLightBox, LightBox, Photo Gallery, Online Picture Gallery, Photo Album Creator" />
		<meta name="description" content="Photo created with VisualLightBox, a free wizard program that helps you easily generate beautiful Lightbox-style web photo galleries" />
		<link rel="shortcut icon" href="favicon.ico" />
		
		<!-- Start VisualLightBox.com HEAD section -->
		<link rel="stylesheet" href="engine/css/vlightbox1.css" type="text/css" />
		<link rel="stylesheet" href="engine/css/visuallightbox.css" type="text/css" media="screen" />
<script src="engine/js/jquery.min.js" type="text/javascript"></script>
		<script src="engine/js/visuallightbox.js" type="text/javascript"></script>
		<!-- End VisualLightBox.com HEAD section -->
		
	</head>
	<body>
	
	<!-- Start VisualLightBox.com BODY section id=1 -->
	
    
	<script src="engine/js/vlbdata1.js" type="text/javascript"></script>
	<!-- End VisualLightBox.com BODY section -->
	
	</body>
</html>


<artisteer:Article ID="Article1"  Caption="Illness - Thrush" runat="server"><ContentTemplate>
    
    
    
<div id="vlightbox1">
	<a class="vlightbox1" href="data/images1/7.jpg" title="Thrush">
    <img src="data/thumbnails1/7.jpg" alt="Jake Duldulao" style="float:left;border:0; width:100px; margin: 0 1em 0 0;"/>
    </a>
	</div>
    <p>• It is a fungoid infection of the throat especially in children or of the Vigina.</p>
    <p>The most common symptoms of thrush are white patches that stick to the inside of the mouth and tongue. See a picture of thrush .
In babies, it is easy to mistake thrush for milk or formula. It looks like cottage cheese or milk curds. Don't try to wipe away these patches, 
because you can make them red and sore.  Some babies with thrush can be cranky and do not want to eat. Thrush is a yeast infection that causes white patches in the mouth and on the tongue. 
Thrush is most common in babies and older adults, but it can occur at any age.
Thrush in babies is usually not serious, and you can treat it with 
antifungal medicine such as nystatin liquid. In most cases, 
you will put the medicine directly on the white patches. 
When a baby has thrush, the yeast can cause a diaper rash at the 
same time as thrush. Your baby may need nystatin cream or ointment for his or her diaper area.
To treat thrush in adults, at first you will probably use medicine that
 goes directly on the white patches, such as a liquid or a lozenge.
 If these medicines don't work, your doctor may prescribe an antifungal pill.</p>
    <p>
    	<span class="art-button-wrapper">
    		<span class="l"> </span>
    		<span class="r"> </span>
    		<a class="art-button" href="javascript:void(0)">Read more...</a>
    	</span>
    </p>


    
   

           </ContentTemplate></artisteer:Article>


  
    

</asp:Content>

